Coffyy/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('login.urls')),  # Include login URLs
    path('account-profile/', include('account_profile.urls')),  #purchase-order URLs
    path('dashboard/', include('dashboard.urls')), #ge test ra nakong sidebar ani abi. ilisi lang niya ni sa imoha
    path('item-list/', include('item_list.urls')),  # Include item_list URLs
    path('item-category/', include('item_category.urls')),  # Include the app's URLs
    path('purchase-order/', include('purchase_order.urls')),  #purchase-order URLs
    path('supplier/', include('supplier.urls')),
    path('item-request/', include('item_request.urls') ),
    path('employees/', include('employee_manage.urls')),
]

account_profile/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from login import views as login_views



app_name = 'account_profile'  # Namespace for the app

urlpatterns = [
    path('login/', login_views.index, name='login_index'),  # Login redirection
    path('', views.view_account, name='view_account'),  # Load page and display data
    path('edit-page/', views.view_account, name='edit_account_page'),  # Load edit page
    path('edit/', views.edit_account, name='edit_account'),  # URL for editing account
    path('update-password/', views.update_password, name='update_password'),  # New URL for password update
    path("delete-account/", views.delete_accounts, name="delete_account"), # URL for deleting account
]

dashboard/urls.py
from django.urls import path
from . import views

app_name = "dashboard"  # Use `app_name` instead of `appname`
urlpatterns = [
    path("", views.index, name="index")
]

item_list/urls.py
from django.urls import path
from . import views

app_name = 'item_list'  # Namespace for the app

urlpatterns = [
    path('', views.index, name='item_list_index'),  # URL pattern for item_list_index
    path('add/', views.add_item, name='add_item'),  # New URL pattern for add_item
    path('cancel_redirect/', views.cancel_redirect, name='cancel_redirect'),  # Add this line
    path('delete/', views.delete_items, name='delete_items'),
    path('search-items/', views.search_items, name='search_items'),
    path('search-items-edit/', views.search_items_edit, name='search_items_edit'),
    path('edit/<int:item_id>/', views.edit_item, name='edit_item'),
    path('check-item-name/', views.check_item_name, name='check_item_name'),
    path('check-item-name-edit/', views.check_item_name, name='check_item_name_edit'),
]

login/urls.py
from django.urls import path
from . import views

app_name = 'login'  # Define the namespace for the app

urlpatterns = [
    path('', views.index, name='login_index'),  # Root URL points to the index view
    path('register/', views.register, name='register'),
    path('forgot-password/', views.forgot_pass, name='forgot_pass'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}My Django App{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
	<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
    <link href="https://cdn.lineicons.com/5.0/lineicons.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">

    {% block stylesheet %}
    {% endblock stylesheet %}
</head>
<body>

    <div id="right-popup" class="right-popup">
        <div class="popup-content">
            <span id="popup-message"></span>
        </div>
    </div>
    
    {% if messages %}
        <div style="display:none;"> <!-- Hide messages but include them for the script -->
            {% for message in messages %}
                <p>{{ message }}</p>
            {% endfor %}
        </div>
    {% endif %}
    
    <div class="custom-header">
        <div class="header-logo">
            <img src="{% static 'images/logo.png' %}" alt="Logo">
        </div>
        <div class="header-user">
            <div class="header-user">
                {% if request.session.username %}
                    Welcome, {{ request.session.username }}!
                {% else %}
                    Welcome, Guest!
                {% endif %}
            </div>
        </div>
    </div>
    <div class="wrapper">
        <aside id="sidebar">
            <div class="d-flex">
                <button id="toggle-btn" type="button">
                    <i class="lni lni-menu-hamburger-1"></i>
                </button>
                <div class="sidebar-logo">
                    {% comment %} <img src="{% static 'images/logo.png' %}" alt="Logo" width=80px> {% endcomment %}

                    <a href="#"></a>
                </div>
            </div>
            <ul class="sidebar-nav">
                <li class="sidebar-item">
                    <a href="#" class="sidebar-link has-dropdown collapsed" data-bs-toggle="collapse" data-bs-target="#account-profile"
                        aria-expanded="false" aria-controls="account-profile">
                        <i class="lni lni-user-4"></i>
                        <span>Account Profile</span>
                    </a>
                    <ul id="account-profile" class="sidebar-dropdown list-unstyled collapse" data-bs-parent="#sidebar">

                        <li class="sidebar-item">
                            <a href="{% url 'login:login_index' %}" class="sidebar-link">Sign Out</a>
                        </li>
                        <li class="sidebar-item">
                            <a href="{% url 'account_profile:edit_account_page' %}" class="sidebar-link">Edit Account</a>
                        </li>
                    </ul>
                </li>
                <li class="sidebar-item">
                    <a href="{% url 'dashboard:index' %}" class="sidebar-link">
                        <i class="lni lni-dashboard-square-1"></i>
                        <span>Dashboard</span>
                    </a>
                </li>
                <li class="sidebar-item">
                    <a href="#" class="sidebar-link has-dropdown collapsed" data-bs-toggle="collapse" data-bs-target="#items"
                        aria-expanded="false" aria-controls="items">
                        <i class="lni lni-basket-shopping-3"></i>
                        <span>Items</span>
                    </a>
                    <ul id="items" class="sidebar-dropdown list-unstyled collapse" data-bs-parent="#sidebar">
                        <li class="sidebar-item">
                            <a href="{% url 'item_list:item_list_index' %}?page=1&rows=10" class="sidebar-link">Item List</a>
                        </li>
                        <li class="sidebar-item">
                            <a href="{% url 'item_categories_index' %}?page=1&rows=10" class="sidebar-link">Item Categories</a>
                        </li>
                    </ul>
                </li>
                <li class="sidebar-item">
                    <a href="#" class="sidebar-link has-dropdown collapsed" data-bs-toggle="collapse" data-bs-target="#inventory-management"
                        aria-expanded="false" aria-controls="inventory-management">
                        <i class="lni lni-cart-1"></i>
                        <span>Inventory Management</span>
                    </a>
                    <ul id="inventory-management" class="sidebar-dropdown list-unstyled collapse" data-bs-parent="#sidebar">
                        <li class="sidebar-item">
                              <a href="{% url 'purchase-order' %}?page=1&rows=10" class="sidebar-link">Purchase Order</a>
                        </li>

                        <li class="sidebar-item">
                            <a href="{% url 'item-request' %}?page=1&rows=10" class="sidebar-link">Item Requests</a>
                        </li>
                        {% if request.session.role == 'owner' %} 
                        <li class="sidebar-item">
                            <a href="{% url 'suppliers' %}?page=1&rows=10"" class="sidebar-link">Suppliers</a>
                        </li>
                        {% endif %}

                    </ul>
                </li>
                {% if request.session.role == 'owner' %} 
                <li class="sidebar-item">
                    <a href="{% url 'employee_list' %}" class="sidebar-link">
                        <i class="lni lni-user-multiple-4"></i>
                        <span>Employees</span>
                    </a>
                </li>
                {% endif %}
                <li class="sidebar-item">
                    <a href="#" class="sidebar-link">
                        <i class="lni lni-gear-1"></i>
                        <span>Settings</span>
                    </a>
                </li>
            </ul>
        </aside>
        <div class="main p-3">
            <div class="text-center">
                {% block content %}
                <!-- Page-specific content goes here -->
                {% endblock content %}
            </div>
        </div>
    </div>
    <div class="custom-footer">
    </div>
{% comment %} 
    <footer>
    </footer> {% endcomment %}
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'js/script.js' %}"></script>
    {% block scripts %}
    {% endblock scripts %}
</body>
</html>